### ISSUE TITLE
Release a new version 

### ISSUE THREAD

**Issue by romank0** [ployst/component-builder#52]
The latest master has some fixes which are not released yet.

**Comment by txels** [comment]
Oh hi @romank0 thanks for pointing that out.

**Comment by txels** [comment]
Hmm yes I see what happened. This used to be built and auto-released from CircleCI. Before the latest change, circle CI deprecated its 1.0 version and forced us to migrate to the backwards-incompatible 2.0 version. All old builds stopped working. I see we spent some time trying to set up a 2.0 build but did not succeed, and possibly moved on to something else and forgot 🤦‍♂

**Comment by txels** [comment]
Upgrading to 2.0 is a pain, I will try and at least release the latest version manually.

**Comment by txels** [comment]
BTW out of curiosity, what kind of project are you using component-builder for?

**Comment by romank0** [comment]
I'm using it for old good AZS.

**Comment by txels** [comment]
Ah OK yes I was under the impression you no longer worked there 😅

**Comment by txels** [comment]
I just released a version 1.1.2 from latest master. Enjoy!
